name: Halloween
main: com.skyost.october.Halloween
description: Plugin for Halloween events.
version: 0.7
author: Skyost
website: http://www.skyost.eu
softdepend: [Citizens, Vault]
commands:
 scare:
  description: Scare a player.
  usage: /scare <player> [id].
  permission: halloween.scare
 haunt:
  description: Haunt a player.
  usage: /haunt <player> [time].
  permission: halloween.haunt
permissions:
 halloween.scare:
  default: true
  description: Allow you to scare a player.
 halloween.haunt:
  default: true
  description: Allow you to haunt a player.
 halloween.events.bypass:
  default: false
  description: Allow you to bypass random events.
 halloween.curses.bypass:
  default: false
  description: Allow you to bypass curses.
